=== egovernments/eGov1/egov/egov-egi/src/main/java/org/egov/infra/events/entity/schema/ResponseTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:complexType name="CallBackType">
		<xsd:sequence>
			<xsd:element name="bean" type="xsd:string" maxOccurs="1"
				minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>


	<xsd:complexType name="EmailType">
		<xsd:sequence>
			<xsd:element name="to" type="xsd:string" maxOccurs="unbounded"
				minOccurs="1" />

			<xsd:element name="cc" type="xsd:string" maxOccurs="unbounded"
				minOccurs="0" />

			<xsd:element name="bcc" type="xsd:string" maxOccurs="unbounded"
				minOccurs="0" />

			<xsd:element name="subject" type="xsd:string" maxOccurs="1"
				minOccurs="0" />
			<xsd:element name="body" type="xsd:string" maxOccurs="1"
				minOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="SMSType">
		<xsd:sequence>
			<xsd:element name="phonenumber" type="xsd:string"
				maxOccurs="unbounded" minOccurs="1" />
			<xsd:element name="message" type="xsd:string" maxOccurs="1"
				minOccurs="1" />

		</xsd:sequence>
	</xsd:complexType>

	<xsd:element name="response">
		<xsd:complexType>
			<xsd:sequence minOccurs="1">
				<xsd:element name="callback" type="CallBackType"
					maxOccurs="1" minOccurs="0" />
				<xsd:element name="email" type="EmailType" maxOccurs="unbounded"
					minOccurs="0" />
				<xsd:element name="sms" type="SMSType" maxOccurs="unbounded"
					minOccurs="0" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== egovernments/eGov1/egov/egov-egi/src/main/java/org/egov/infra/events/entity/schema/Response.xml
<?xml version="1.0" encoding="UTF-8"?>
<response xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ResponseTypes.xsd">

	<callback>
		<bean>
	org.egov.bean.eventCallbackBean
	</bean>
	</callback>
	<email>
		<to>ro@coc.gov.in</to>
		<cc>${cc_address}</cc>
		<body>
		    Dear ${to_name},
		    The following receipt has been cancelled -
		    lorem ipsum ${receipt_no} dolor
		    lorem dolor
 		</body>
	</email>
	<email>
		<to>ro@coc.gov.in</to>
		<cc>${cc_address}</cc>
		<body>
            Dear ${to_name},
            The following receipt has been cancelled -
            lorem ipsum ${receipt_no} dolor
            lorem dolor
        </body>
	</email>
	<sms>
		<phonenumber>11111</phonenumber>
		<message> lorem ipsum ${receipt_no} dolor </message>
	</sms>
	<sms>
		<phonenumber>11111</phonenumber>
		<message> lorem ipsum ${receipt_no} dolor </message>
	</sms>
</response>
